-- MySQL Script generated by MySQL Workbench
-- Mon Jul 14 11:40:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema arriendo_bicicletas_urbanas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema arriendo_bicicletas_urbanas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `arriendo_bicicletas_urbanas` DEFAULT CHARACTER SET utf8mb3 ;
USE `arriendo_bicicletas_urbanas` ;

-- -----------------------------------------------------
-- Table `arriendo_bicicletas_urbanas`.`estaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arriendo_bicicletas_urbanas`.`estaciones` (
  `id_estacion` INT NOT NULL AUTO_INCREMENT,
  `nombre_estacion` VARCHAR(120) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `capacidad_maxima` INT NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_estacion`),
  UNIQUE INDEX `id_estacione_UNIQUE` (`id_estacion` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `arriendo_bicicletas_urbanas`.`estados_bicicletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arriendo_bicicletas_urbanas`.`estados_bicicletas` (
  `id_estados_bicicleta` INT NOT NULL,
  `descripcion_estado` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `estados_bicicletascol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estados_bicicleta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arriendo_bicicletas_urbanas`.`tipo_bicicletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arriendo_bicicletas_urbanas`.`tipo_bicicletas` (
  `id_tipo_bicicleta` INT NOT NULL,
  `descripcion_tipo` VARCHAR(100) NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_bicicleta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arriendo_bicicletas_urbanas`.`bicicletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arriendo_bicicletas_urbanas`.`bicicletas` (
  `id_bicicleta` INT NOT NULL AUTO_INCREMENT,
  `estacion_asignada` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `Estaciones_id_estacione` INT NOT NULL,
  `id_estados_bicicleta` INT NOT NULL,
  `id_tipo_bicicleta` INT NOT NULL,
  PRIMARY KEY (`id_bicicleta`, `Estaciones_id_estacione`, `id_estados_bicicleta`, `id_tipo_bicicleta`),
  UNIQUE INDEX `id_bicicleta_UNIQUE` (`id_bicicleta` ASC) VISIBLE,
  INDEX `fk_Bicicletas_Estaciones1_idx` (`Estaciones_id_estacione` ASC) VISIBLE,
  INDEX `fk_bicicletas_estados_bicicletas1_idx` (`id_estados_bicicleta` ASC) VISIBLE,
  INDEX `fk_bicicletas_tipo_bicicletas1_idx` (`id_tipo_bicicleta` ASC) VISIBLE,
  CONSTRAINT `fk_Bicicletas_Estaciones1`
    FOREIGN KEY (`Estaciones_id_estacione`)
    REFERENCES `arriendo_bicicletas_urbanas`.`estaciones` (`id_estacion`),
  CONSTRAINT `fk_bicicletas_estados_bicicletas1`
    FOREIGN KEY (`id_estados_bicicleta`)
    REFERENCES `arriendo_bicicletas_urbanas`.`estados_bicicletas` (`id_estados_bicicleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bicicletas_tipo_bicicletas1`
    FOREIGN KEY (`id_tipo_bicicleta`)
    REFERENCES `arriendo_bicicletas_urbanas`.`tipo_bicicletas` (`id_tipo_bicicleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `arriendo_bicicletas_urbanas`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arriendo_bicicletas_urbanas`.`tipo_usuarios` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `descripcion_tipo` VARCHAR(60) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo`),
  UNIQUE INDEX `id_tipo_UNIQUE` (`id_tipo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `arriendo_bicicletas_urbanas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arriendo_bicicletas_urbanas`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `Tipo_usuario_id` INT NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `rut` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(80) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuarios`, `Tipo_usuario_id`),
  UNIQUE INDEX `id_usuarios_UNIQUE` (`id_usuarios` ASC) VISIBLE,
  INDEX `fk_Usuarios_Tipo_usuarios_idx` (`Tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Tipo_usuarios`
    FOREIGN KEY (`Tipo_usuario_id`)
    REFERENCES `arriendo_bicicletas_urbanas`.`tipo_usuarios` (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `arriendo_bicicletas_urbanas`.`arriendos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arriendo_bicicletas_urbanas`.`arriendos` (
  `id_arriendo` INT NOT NULL AUTO_INCREMENT,
  `descripcion_arriendo` VARCHAR(170) NULL,
  `id_bicicleta` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha_inicio` DATETIME NULL DEFAULT NULL,
  `fecha_fin` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `estacion_inicio` INT NOT NULL,
  `estacion_fin` INT NOT NULL,
  PRIMARY KEY (`id_arriendo`, `id_bicicleta`, `id_usuario`, `estacion_inicio`, `estacion_fin`),
  UNIQUE INDEX `id_arriendo_UNIQUE` (`id_arriendo` ASC) VISIBLE,
  INDEX `fk_Arriendos_Bicicletas1_idx` (`id_bicicleta` ASC) VISIBLE,
  INDEX `fk_Arriendos_Usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_arriendos_estaciones1_idx` (`estacion_inicio` ASC) VISIBLE,
  INDEX `fk_arriendos_estaciones2_idx` (`estacion_fin` ASC) VISIBLE,
  CONSTRAINT `fk_Arriendos_Bicicletas1`
    FOREIGN KEY (`id_bicicleta`)
    REFERENCES `arriendo_bicicletas_urbanas`.`bicicletas` (`id_bicicleta`),
  CONSTRAINT `fk_Arriendos_Usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `arriendo_bicicletas_urbanas`.`usuarios` (`id_usuarios`),
  CONSTRAINT `fk_arriendos_estaciones1`
    FOREIGN KEY (`estacion_inicio`)
    REFERENCES `arriendo_bicicletas_urbanas`.`estaciones` (`id_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arriendos_estaciones2`
    FOREIGN KEY (`estacion_fin`)
    REFERENCES `arriendo_bicicletas_urbanas`.`estaciones` (`id_estacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `arriendo_bicicletas_urbanas`.`historial_uso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arriendo_bicicletas_urbanas`.`historial_uso` (
  `id_Historial` INT NOT NULL AUTO_INCREMENT,
  `Bicicletas_id_bicicleta` INT NOT NULL,
  `registro_historial` VARCHAR(500) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_Historial`, `Bicicletas_id_bicicleta`),
  UNIQUE INDEX `id_Historial_UNIQUE` (`id_Historial` ASC) VISIBLE,
  INDEX `fk_Historial_uso_Bicicletas1_idx` (`Bicicletas_id_bicicleta` ASC) VISIBLE,
  CONSTRAINT `fk_Historial_uso_Bicicletas1`
    FOREIGN KEY (`Bicicletas_id_bicicleta`)
    REFERENCES `arriendo_bicicletas_urbanas`.`bicicletas` (`id_bicicleta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `arriendo_bicicletas_urbanas`.`multas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arriendo_bicicletas_urbanas`.`multas` (
  `id_Multa` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  `multa_desc` VARCHAR(500) NULL DEFAULT NULL,
  `usuarios_id_usuarios` INT NOT NULL,
  `usuarios_Tipo_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_Multa`, `usuarios_id_usuarios`, `usuarios_Tipo_usuario_id`),
  UNIQUE INDEX `id_Multa_UNIQUE` (`id_Multa` ASC) VISIBLE,
  INDEX `fk_multas_usuarios1_idx` (`usuarios_id_usuarios` ASC, `usuarios_Tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_multas_usuarios1`
    FOREIGN KEY (`usuarios_id_usuarios` , `usuarios_Tipo_usuario_id`)
    REFERENCES `arriendo_bicicletas_urbanas`.`usuarios` (`id_usuarios` , `Tipo_usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
